version: '3'

services:
  zipkin_storage_mysql:
    image: mysql:5.7
    #restart: always
    # command: --default-authentication-plugin=mysql_native_password
    ports:
      - ${MYSQL_PORT}:3306    
    volumes:
      - /mysql_test:/var/lib/mysql

    networks:
        default:
            aliases:
                - zipkin_mysql  
                
    deploy:
        placement:
         constraints: 
           - node.hostname == ${HOSTNAME}
        restart_policy:
          condition: any
          max_attempts: 3
        resources:
            limits:
                cpus: '0.5'
                memory: 512M
        update_config:
            failure_action: rollback
            parallelism: 1
            delay: 30s
            monitor: 30s
   
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PWD}
      - MYSQL_DATABASE=zipkin
      - MYSQL_USER=zipkin
      - MYSQL_PASSWORD=${MYSQL_PWD}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - JAVA_OPTS=-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxMetaspaceSize=100M -Xms256M -Xmx256M 
#volumes:
#  zipkin:
#    driver: local

networks:
  default:
    external:
      name: ${NETWORK}
